// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// DI_ms2_ranges
DataFrame DI_ms2_ranges(const String& filename, const bool& collapse_overlaps, const bool& debug);
RcppExport SEXP _mzkitcpp_DI_ms2_ranges(SEXP filenameSEXP, SEXP collapse_overlapsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const bool& >::type collapse_overlaps(collapse_overlapsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(DI_ms2_ranges(filename, collapse_overlaps, debug));
    return rcpp_result_gen;
END_RCPP
}
// DI_ms3_targets
DataFrame DI_ms3_targets(const String& filename, const bool& debug);
RcppExport SEXP _mzkitcpp_DI_ms3_targets(SEXP filenameSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(DI_ms3_targets(filename, debug));
    return rcpp_result_gen;
END_RCPP
}
// DI_slice_library
List DI_slice_library(const DataFrame& ms2_ranges, const DataFrame& lipid_library, const bool& is_mark_unique_as_diagnostic, const bool& debug);
RcppExport SEXP _mzkitcpp_DI_slice_library(SEXP ms2_rangesSEXP, SEXP lipid_librarySEXP, SEXP is_mark_unique_as_diagnosticSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type ms2_ranges(ms2_rangesSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type lipid_library(lipid_librarySEXP);
    Rcpp::traits::input_parameter< const bool& >::type is_mark_unique_as_diagnostic(is_mark_unique_as_diagnosticSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(DI_slice_library(ms2_ranges, lipid_library, is_mark_unique_as_diagnostic, debug));
    return rcpp_result_gen;
END_RCPP
}
// DI_unslice_library
DataFrame DI_unslice_library(const List& sliced_lib, const bool& debug);
RcppExport SEXP _mzkitcpp_DI_unslice_library(SEXP sliced_libSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type sliced_lib(sliced_libSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(DI_unslice_library(sliced_lib, debug));
    return rcpp_result_gen;
END_RCPP
}
// DI_encoded_search_params
String DI_encoded_search_params(const List& search_params, const bool& debug);
RcppExport SEXP _mzkitcpp_DI_encoded_search_params(SEXP search_paramsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type search_params(search_paramsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(DI_encoded_search_params(search_params, debug));
    return rcpp_result_gen;
END_RCPP
}
// DI_summarized_compounds
DataFrame DI_summarized_compounds(const DataFrame& di_search_results, const List& search_lib, const DataFrame& ms2_ranges, const String& adducts_file, const bool& debug);
RcppExport SEXP _mzkitcpp_DI_summarized_compounds(SEXP di_search_resultsSEXP, SEXP search_libSEXP, SEXP ms2_rangesSEXP, SEXP adducts_fileSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type di_search_results(di_search_resultsSEXP);
    Rcpp::traits::input_parameter< const List& >::type search_lib(search_libSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type ms2_ranges(ms2_rangesSEXP);
    Rcpp::traits::input_parameter< const String& >::type adducts_file(adducts_fileSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(DI_summarized_compounds(di_search_results, search_lib, ms2_ranges, adducts_file, debug));
    return rcpp_result_gen;
END_RCPP
}
// DI_peakgroups_and_peaks
List DI_peakgroups_and_peaks(const DataFrame& di_search_results_no_frags, const int& first_peak_id, const int& first_group_id, const int& num_peakgroups, const String& search_name, const String& library_name, const bool& verbose, const bool& debug);
RcppExport SEXP _mzkitcpp_DI_peakgroups_and_peaks(SEXP di_search_results_no_fragsSEXP, SEXP first_peak_idSEXP, SEXP first_group_idSEXP, SEXP num_peakgroupsSEXP, SEXP search_nameSEXP, SEXP library_nameSEXP, SEXP verboseSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type di_search_results_no_frags(di_search_results_no_fragsSEXP);
    Rcpp::traits::input_parameter< const int& >::type first_peak_id(first_peak_idSEXP);
    Rcpp::traits::input_parameter< const int& >::type first_group_id(first_group_idSEXP);
    Rcpp::traits::input_parameter< const int& >::type num_peakgroups(num_peakgroupsSEXP);
    Rcpp::traits::input_parameter< const String& >::type search_name(search_nameSEXP);
    Rcpp::traits::input_parameter< const String& >::type library_name(library_nameSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(DI_peakgroups_and_peaks(di_search_results_no_frags, first_peak_id, first_group_id, num_peakgroups, search_name, library_name, verbose, debug));
    return rcpp_result_gen;
END_RCPP
}
// DI_ms3_peakgroups_and_peaks
List DI_ms3_peakgroups_and_peaks(const DataFrame& ms3_search_results_no_frags, const int& first_peak_id, const int& first_group_id, const int& num_peakgroups, const int& num_peaks, const String& search_name, const String& library_name, const bool& verbose, const bool& debug);
RcppExport SEXP _mzkitcpp_DI_ms3_peakgroups_and_peaks(SEXP ms3_search_results_no_fragsSEXP, SEXP first_peak_idSEXP, SEXP first_group_idSEXP, SEXP num_peakgroupsSEXP, SEXP num_peaksSEXP, SEXP search_nameSEXP, SEXP library_nameSEXP, SEXP verboseSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type ms3_search_results_no_frags(ms3_search_results_no_fragsSEXP);
    Rcpp::traits::input_parameter< const int& >::type first_peak_id(first_peak_idSEXP);
    Rcpp::traits::input_parameter< const int& >::type first_group_id(first_group_idSEXP);
    Rcpp::traits::input_parameter< const int& >::type num_peakgroups(num_peakgroupsSEXP);
    Rcpp::traits::input_parameter< const int& >::type num_peaks(num_peaksSEXP);
    Rcpp::traits::input_parameter< const String& >::type search_name(search_nameSEXP);
    Rcpp::traits::input_parameter< const String& >::type library_name(library_nameSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(DI_ms3_peakgroups_and_peaks(ms3_search_results_no_frags, first_peak_id, first_group_id, num_peakgroups, num_peaks, search_name, library_name, verbose, debug));
    return rcpp_result_gen;
END_RCPP
}
// DI_pipeline
List DI_pipeline(const StringVector& samples, const DataFrame& ms2_ranges, const List& is_sliced_lib, const List& is_search_params, const List& sliced_lib, const List& search_params, const String& adducts_file, const int& fragment_group_id_decimals, const bool& debug);
RcppExport SEXP _mzkitcpp_DI_pipeline(SEXP samplesSEXP, SEXP ms2_rangesSEXP, SEXP is_sliced_libSEXP, SEXP is_search_paramsSEXP, SEXP sliced_libSEXP, SEXP search_paramsSEXP, SEXP adducts_fileSEXP, SEXP fragment_group_id_decimalsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type ms2_ranges(ms2_rangesSEXP);
    Rcpp::traits::input_parameter< const List& >::type is_sliced_lib(is_sliced_libSEXP);
    Rcpp::traits::input_parameter< const List& >::type is_search_params(is_search_paramsSEXP);
    Rcpp::traits::input_parameter< const List& >::type sliced_lib(sliced_libSEXP);
    Rcpp::traits::input_parameter< const List& >::type search_params(search_paramsSEXP);
    Rcpp::traits::input_parameter< const String& >::type adducts_file(adducts_fileSEXP);
    Rcpp::traits::input_parameter< const int& >::type fragment_group_id_decimals(fragment_group_id_decimalsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(DI_pipeline(samples, ms2_ranges, is_sliced_lib, is_search_params, sliced_lib, search_params, adducts_file, fragment_group_id_decimals, debug));
    return rcpp_result_gen;
END_RCPP
}
// DI_pipeline_ms3_search
DataFrame DI_pipeline_ms3_search(const StringVector& samples, const List& is_lib, const List& is_search_params, const List& search_lib, const List& search_params, const String& adducts_file, const bool& debug);
RcppExport SEXP _mzkitcpp_DI_pipeline_ms3_search(SEXP samplesSEXP, SEXP is_libSEXP, SEXP is_search_paramsSEXP, SEXP search_libSEXP, SEXP search_paramsSEXP, SEXP adducts_fileSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const List& >::type is_lib(is_libSEXP);
    Rcpp::traits::input_parameter< const List& >::type is_search_params(is_search_paramsSEXP);
    Rcpp::traits::input_parameter< const List& >::type search_lib(search_libSEXP);
    Rcpp::traits::input_parameter< const List& >::type search_params(search_paramsSEXP);
    Rcpp::traits::input_parameter< const String& >::type adducts_file(adducts_fileSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(DI_pipeline_ms3_search(samples, is_lib, is_search_params, search_lib, search_params, adducts_file, debug));
    return rcpp_result_gen;
END_RCPP
}
// DI_search_lib
DataFrame DI_search_lib(const StringVector& samples, const DataFrame& mspLibrary, const double& ms1_ppm, const double& ms2_ppm, const String ms1_scan_filter, const String scan_intensity_summary, const bool& ignore_empty, const float& m_minus_one_intensity_threshold, const float& m_minus_two_intensity_threshold, const bool& debug);
RcppExport SEXP _mzkitcpp_DI_search_lib(SEXP samplesSEXP, SEXP mspLibrarySEXP, SEXP ms1_ppmSEXP, SEXP ms2_ppmSEXP, SEXP ms1_scan_filterSEXP, SEXP scan_intensity_summarySEXP, SEXP ignore_emptySEXP, SEXP m_minus_one_intensity_thresholdSEXP, SEXP m_minus_two_intensity_thresholdSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type mspLibrary(mspLibrarySEXP);
    Rcpp::traits::input_parameter< const double& >::type ms1_ppm(ms1_ppmSEXP);
    Rcpp::traits::input_parameter< const double& >::type ms2_ppm(ms2_ppmSEXP);
    Rcpp::traits::input_parameter< const String >::type ms1_scan_filter(ms1_scan_filterSEXP);
    Rcpp::traits::input_parameter< const String >::type scan_intensity_summary(scan_intensity_summarySEXP);
    Rcpp::traits::input_parameter< const bool& >::type ignore_empty(ignore_emptySEXP);
    Rcpp::traits::input_parameter< const float& >::type m_minus_one_intensity_threshold(m_minus_one_intensity_thresholdSEXP);
    Rcpp::traits::input_parameter< const float& >::type m_minus_two_intensity_threshold(m_minus_two_intensity_thresholdSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(DI_search_lib(samples, mspLibrary, ms1_ppm, ms2_ppm, ms1_scan_filter, scan_intensity_summary, ignore_empty, m_minus_one_intensity_threshold, m_minus_two_intensity_threshold, debug));
    return rcpp_result_gen;
END_RCPP
}
// DI_ms1_and_ms2_intensity
DataFrame DI_ms1_and_ms2_intensity(const StringVector& samples, const NumericVector& ms1_mzs, const NumericVector& ms2_mzs, const double& ms1_ppm, const double& ms2_ppm, const String ms1_scan_filter, const String scan_intensity_summary, const bool& ignore_empty, const float& m_minus_one_intensity_threshold, const float& m_minus_two_intensity_threshold, const bool& debug);
RcppExport SEXP _mzkitcpp_DI_ms1_and_ms2_intensity(SEXP samplesSEXP, SEXP ms1_mzsSEXP, SEXP ms2_mzsSEXP, SEXP ms1_ppmSEXP, SEXP ms2_ppmSEXP, SEXP ms1_scan_filterSEXP, SEXP scan_intensity_summarySEXP, SEXP ignore_emptySEXP, SEXP m_minus_one_intensity_thresholdSEXP, SEXP m_minus_two_intensity_thresholdSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type ms1_mzs(ms1_mzsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type ms2_mzs(ms2_mzsSEXP);
    Rcpp::traits::input_parameter< const double& >::type ms1_ppm(ms1_ppmSEXP);
    Rcpp::traits::input_parameter< const double& >::type ms2_ppm(ms2_ppmSEXP);
    Rcpp::traits::input_parameter< const String >::type ms1_scan_filter(ms1_scan_filterSEXP);
    Rcpp::traits::input_parameter< const String >::type scan_intensity_summary(scan_intensity_summarySEXP);
    Rcpp::traits::input_parameter< const bool& >::type ignore_empty(ignore_emptySEXP);
    Rcpp::traits::input_parameter< const float& >::type m_minus_one_intensity_threshold(m_minus_one_intensity_thresholdSEXP);
    Rcpp::traits::input_parameter< const float& >::type m_minus_two_intensity_threshold(m_minus_two_intensity_thresholdSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(DI_ms1_and_ms2_intensity(samples, ms1_mzs, ms2_mzs, ms1_ppm, ms2_ppm, ms1_scan_filter, scan_intensity_summary, ignore_empty, m_minus_one_intensity_threshold, m_minus_two_intensity_threshold, debug));
    return rcpp_result_gen;
END_RCPP
}
// DI_ms_intensity
DataFrame DI_ms_intensity(const StringVector& samples, const NumericVector& mzs, const double& ppm, const String scan_filter, const String scan_intensity_summary, const int& msLevel, const float& m_minus_one_intensity_threshold, const float& m_minus_two_intensity_threshold, const NumericVector& prec_mzs, const bool& debug);
RcppExport SEXP _mzkitcpp_DI_ms_intensity(SEXP samplesSEXP, SEXP mzsSEXP, SEXP ppmSEXP, SEXP scan_filterSEXP, SEXP scan_intensity_summarySEXP, SEXP msLevelSEXP, SEXP m_minus_one_intensity_thresholdSEXP, SEXP m_minus_two_intensity_thresholdSEXP, SEXP prec_mzsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mzs(mzsSEXP);
    Rcpp::traits::input_parameter< const double& >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< const String >::type scan_filter(scan_filterSEXP);
    Rcpp::traits::input_parameter< const String >::type scan_intensity_summary(scan_intensity_summarySEXP);
    Rcpp::traits::input_parameter< const int& >::type msLevel(msLevelSEXP);
    Rcpp::traits::input_parameter< const float& >::type m_minus_one_intensity_threshold(m_minus_one_intensity_thresholdSEXP);
    Rcpp::traits::input_parameter< const float& >::type m_minus_two_intensity_threshold(m_minus_two_intensity_thresholdSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type prec_mzs(prec_mzsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(DI_ms_intensity(samples, mzs, ppm, scan_filter, scan_intensity_summary, msLevel, m_minus_one_intensity_threshold, m_minus_two_intensity_threshold, prec_mzs, debug));
    return rcpp_result_gen;
END_RCPP
}
// DI_ms1_range_intensity
DataFrame DI_ms1_range_intensity(const StringVector& samples, const NumericVector& prec_mz_min, const NumericVector& prec_mz_max, const int& scan_width, const bool& debug);
RcppExport SEXP _mzkitcpp_DI_ms1_range_intensity(SEXP samplesSEXP, SEXP prec_mz_minSEXP, SEXP prec_mz_maxSEXP, SEXP scan_widthSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type prec_mz_min(prec_mz_minSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type prec_mz_max(prec_mz_maxSEXP);
    Rcpp::traits::input_parameter< const int& >::type scan_width(scan_widthSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(DI_ms1_range_intensity(samples, prec_mz_min, prec_mz_max, scan_width, debug));
    return rcpp_result_gen;
END_RCPP
}
// DI_ms2_range_id
IntegerVector DI_ms2_range_id(const DataFrame& di_ms2_ranges_table, const NumericVector& prec_mzs, const bool& debug);
RcppExport SEXP _mzkitcpp_DI_ms2_range_id(SEXP di_ms2_ranges_tableSEXP, SEXP prec_mzsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type di_ms2_ranges_table(di_ms2_ranges_tableSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type prec_mzs(prec_mzsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(DI_ms2_range_id(di_ms2_ranges_table, prec_mzs, debug));
    return rcpp_result_gen;
END_RCPP
}
// DI_ms3_intensity
DataFrame DI_ms3_intensity(const StringVector& samples, const NumericVector& ms1_mzs, const NumericVector& ms2_mzs, const NumericVector& ms3_mzs, const double& ms3AnalysisMs1PrecursorPpmTolr, const double& ms3PrecursorPpmTolr, const double& ms3FragTol, const bool& isMs3FragTypeInPpm, const String& extraction_type, const bool& debug);
RcppExport SEXP _mzkitcpp_DI_ms3_intensity(SEXP samplesSEXP, SEXP ms1_mzsSEXP, SEXP ms2_mzsSEXP, SEXP ms3_mzsSEXP, SEXP ms3AnalysisMs1PrecursorPpmTolrSEXP, SEXP ms3PrecursorPpmTolrSEXP, SEXP ms3FragTolSEXP, SEXP isMs3FragTypeInPpmSEXP, SEXP extraction_typeSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type ms1_mzs(ms1_mzsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type ms2_mzs(ms2_mzsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type ms3_mzs(ms3_mzsSEXP);
    Rcpp::traits::input_parameter< const double& >::type ms3AnalysisMs1PrecursorPpmTolr(ms3AnalysisMs1PrecursorPpmTolrSEXP);
    Rcpp::traits::input_parameter< const double& >::type ms3PrecursorPpmTolr(ms3PrecursorPpmTolrSEXP);
    Rcpp::traits::input_parameter< const double& >::type ms3FragTol(ms3FragTolSEXP);
    Rcpp::traits::input_parameter< const bool& >::type isMs3FragTypeInPpm(isMs3FragTypeInPpmSEXP);
    Rcpp::traits::input_parameter< const String& >::type extraction_type(extraction_typeSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(DI_ms3_intensity(samples, ms1_mzs, ms2_mzs, ms3_mzs, ms3AnalysisMs1PrecursorPpmTolr, ms3PrecursorPpmTolr, ms3FragTol, isMs3FragTypeInPpm, extraction_type, debug));
    return rcpp_result_gen;
END_RCPP
}
// DI_file_info
DataFrame DI_file_info(const StringVector& samples, const bool& debug);
RcppExport SEXP _mzkitcpp_DI_file_info(SEXP samplesSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(DI_file_info(samples, debug));
    return rcpp_result_gen;
END_RCPP
}
// get_eic
DataFrame get_eic(const StringVector& samples, const double mzmin, const double mzmax, double rtmin, double rtmax, const int mslevel, const int smoothWindow, const bool& debug);
RcppExport SEXP _mzkitcpp_get_eic(SEXP samplesSEXP, SEXP mzminSEXP, SEXP mzmaxSEXP, SEXP rtminSEXP, SEXP rtmaxSEXP, SEXP mslevelSEXP, SEXP smoothWindowSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const double >::type mzmin(mzminSEXP);
    Rcpp::traits::input_parameter< const double >::type mzmax(mzmaxSEXP);
    Rcpp::traits::input_parameter< double >::type rtmin(rtminSEXP);
    Rcpp::traits::input_parameter< double >::type rtmax(rtmaxSEXP);
    Rcpp::traits::input_parameter< const int >::type mslevel(mslevelSEXP);
    Rcpp::traits::input_parameter< const int >::type smoothWindow(smoothWindowSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(get_eic(samples, mzmin, mzmax, rtmin, rtmax, mslevel, smoothWindow, debug));
    return rcpp_result_gen;
END_RCPP
}
// reextract_peaks
DataFrame reextract_peaks(const DataFrame& compound_list, const String& sample_file, const String& intensity_type, const int& mslevel, const int& baselineSmoothingWindow, const int& baselineDropTopX, const bool& verbose, const bool& debug);
RcppExport SEXP _mzkitcpp_reextract_peaks(SEXP compound_listSEXP, SEXP sample_fileSEXP, SEXP intensity_typeSEXP, SEXP mslevelSEXP, SEXP baselineSmoothingWindowSEXP, SEXP baselineDropTopXSEXP, SEXP verboseSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type compound_list(compound_listSEXP);
    Rcpp::traits::input_parameter< const String& >::type sample_file(sample_fileSEXP);
    Rcpp::traits::input_parameter< const String& >::type intensity_type(intensity_typeSEXP);
    Rcpp::traits::input_parameter< const int& >::type mslevel(mslevelSEXP);
    Rcpp::traits::input_parameter< const int& >::type baselineSmoothingWindow(baselineSmoothingWindowSEXP);
    Rcpp::traits::input_parameter< const int& >::type baselineDropTopX(baselineDropTopXSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(reextract_peaks(compound_list, sample_file, intensity_type, mslevel, baselineSmoothingWindow, baselineDropTopX, verbose, debug));
    return rcpp_result_gen;
END_RCPP
}
// repick_peaks
DataFrame repick_peaks(const DataFrame& peaks_to_repick, const String& encodedParams, const bool& verbose, const bool& debug);
RcppExport SEXP _mzkitcpp_repick_peaks(SEXP peaks_to_repickSEXP, SEXP encodedParamsSEXP, SEXP verboseSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type peaks_to_repick(peaks_to_repickSEXP);
    Rcpp::traits::input_parameter< const String& >::type encodedParams(encodedParamsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(repick_peaks(peaks_to_repick, encodedParams, verbose, debug));
    return rcpp_result_gen;
END_RCPP
}
// get_ms2_scans
DataFrame get_ms2_scans(const DataFrame& samples_table, const double& ppm, const int dataLimit, const bool& debug);
RcppExport SEXP _mzkitcpp_get_ms2_scans(SEXP samples_tableSEXP, SEXP ppmSEXP, SEXP dataLimitSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type samples_table(samples_tableSEXP);
    Rcpp::traits::input_parameter< const double& >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< const int >::type dataLimit(dataLimitSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(get_ms2_scans(samples_table, ppm, dataLimit, debug));
    return rcpp_result_gen;
END_RCPP
}
// get_standard_rts
DataFrame get_standard_rts(const DataFrame& samples, const DataFrame& standards, const double& mzTolerance, const double& rtTolerance, const double& minIntensity, const bool& verbose, const bool& debug);
RcppExport SEXP _mzkitcpp_get_standard_rts(SEXP samplesSEXP, SEXP standardsSEXP, SEXP mzToleranceSEXP, SEXP rtToleranceSEXP, SEXP minIntensitySEXP, SEXP verboseSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type standards(standardsSEXP);
    Rcpp::traits::input_parameter< const double& >::type mzTolerance(mzToleranceSEXP);
    Rcpp::traits::input_parameter< const double& >::type rtTolerance(rtToleranceSEXP);
    Rcpp::traits::input_parameter< const double& >::type minIntensity(minIntensitySEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(get_standard_rts(samples, standards, mzTolerance, rtTolerance, minIntensity, verbose, debug));
    return rcpp_result_gen;
END_RCPP
}
// get_last_rts
DataFrame get_last_rts(const DataFrame& samples, const bool& verbose, const bool& debug);
RcppExport SEXP _mzkitcpp_get_last_rts(SEXP samplesSEXP, SEXP verboseSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(get_last_rts(samples, verbose, debug));
    return rcpp_result_gen;
END_RCPP
}
// ISO_isotope_matrices
DataFrame ISO_isotope_matrices(const String& mzML_directory, const DataFrame& sample_tbl, const DataFrame& peak_tbl, const DataFrame& group_tbl, const StringVector& unlabeled_samples, const StringVector& labeled_samples, const List params, const bool& debug);
RcppExport SEXP _mzkitcpp_ISO_isotope_matrices(SEXP mzML_directorySEXP, SEXP sample_tblSEXP, SEXP peak_tblSEXP, SEXP group_tblSEXP, SEXP unlabeled_samplesSEXP, SEXP labeled_samplesSEXP, SEXP paramsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type mzML_directory(mzML_directorySEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type sample_tbl(sample_tblSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type peak_tbl(peak_tblSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type group_tbl(group_tblSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type unlabeled_samples(unlabeled_samplesSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type labeled_samples(labeled_samplesSEXP);
    Rcpp::traits::input_parameter< const List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(ISO_isotope_matrices(mzML_directory, sample_tbl, peak_tbl, group_tbl, unlabeled_samples, labeled_samples, params, debug));
    return rcpp_result_gen;
END_RCPP
}
// maldesi_search
DataFrame maldesi_search(const String& sample_file, const DataFrame& library, const List& search_params, const bool& verbose, const bool& debug);
RcppExport SEXP _mzkitcpp_maldesi_search(SEXP sample_fileSEXP, SEXP librarySEXP, SEXP search_paramsSEXP, SEXP verboseSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type sample_file(sample_fileSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type library(librarySEXP);
    Rcpp::traits::input_parameter< const List& >::type search_params(search_paramsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(maldesi_search(sample_file, library, search_params, verbose, debug));
    return rcpp_result_gen;
END_RCPP
}
// maldesi_isotopic_envelope_finder
DataFrame maldesi_isotopic_envelope_finder(const String& sample_file, const List& params, const bool& verbose, const bool& debug);
RcppExport SEXP _mzkitcpp_maldesi_isotopic_envelope_finder(SEXP sample_fileSEXP, SEXP paramsSEXP, SEXP verboseSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type sample_file(sample_fileSEXP);
    Rcpp::traits::input_parameter< const List& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(maldesi_isotopic_envelope_finder(sample_file, params, verbose, debug));
    return rcpp_result_gen;
END_RCPP
}
// maldesi_create_modified_mzML
void maldesi_create_modified_mzML(const String& sample_file, const String& modified_sample_file, const List& modification_params, const bool& verbose, const bool& debug);
RcppExport SEXP _mzkitcpp_maldesi_create_modified_mzML(SEXP sample_fileSEXP, SEXP modified_sample_fileSEXP, SEXP modification_paramsSEXP, SEXP verboseSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type sample_file(sample_fileSEXP);
    Rcpp::traits::input_parameter< const String& >::type modified_sample_file(modified_sample_fileSEXP);
    Rcpp::traits::input_parameter< const List& >::type modification_params(modification_paramsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    maldesi_create_modified_mzML(sample_file, modified_sample_file, modification_params, verbose, debug);
    return R_NilValue;
END_RCPP
}
// smoothed_series
DataFrame smoothed_series(const NumericVector& data, const StringVector& types, const IntegerVector& windowSizes, bool debug);
RcppExport SEXP _mzkitcpp_smoothed_series(SEXP dataSEXP, SEXP typesSEXP, SEXP windowSizesSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type types(typesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type windowSizes(windowSizesSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(smoothed_series(data, types, windowSizes, debug));
    return rcpp_result_gen;
END_RCPP
}
// monoiosotopic_mass
DataFrame monoiosotopic_mass(const StringVector& formula, int num_digits, bool debug);
RcppExport SEXP _mzkitcpp_monoiosotopic_mass(SEXP formulaSEXP, SEXP num_digitsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type formula(formulaSEXP);
    Rcpp::traits::input_parameter< int >::type num_digits(num_digitsSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(monoiosotopic_mass(formula, num_digits, debug));
    return rcpp_result_gen;
END_RCPP
}
// precursor_mass
DataFrame precursor_mass(const StringVector& formula, const StringVector& adduct, int num_digits, bool debug);
RcppExport SEXP _mzkitcpp_precursor_mass(SEXP formulaSEXP, SEXP adductSEXP, SEXP num_digitsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type formula(formulaSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type adduct(adductSEXP);
    Rcpp::traits::input_parameter< int >::type num_digits(num_digitsSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(precursor_mass(formula, adduct, num_digits, debug));
    return rcpp_result_gen;
END_RCPP
}
// exact_mass
double exact_mass(const String& formula, bool verbose);
RcppExport SEXP _mzkitcpp_exact_mass(SEXP formulaSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type formula(formulaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(exact_mass(formula, verbose));
    return rcpp_result_gen;
END_RCPP
}
// exact_mass_peptide
double exact_mass_peptide(const String& peptideSequence, bool verbose);
RcppExport SEXP _mzkitcpp_exact_mass_peptide(SEXP peptideSequenceSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type peptideSequence(peptideSequenceSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(exact_mass_peptide(peptideSequence, verbose));
    return rcpp_result_gen;
END_RCPP
}
// envelope_dist_peptide
DataFrame envelope_dist_peptide(const String& peptideSequence, double threshold, bool debug);
RcppExport SEXP _mzkitcpp_envelope_dist_peptide(SEXP peptideSequenceSEXP, SEXP thresholdSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type peptideSequence(peptideSequenceSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(envelope_dist_peptide(peptideSequence, threshold, debug));
    return rcpp_result_gen;
END_RCPP
}
// adductize_exact_mass
double adductize_exact_mass(const double& exact_mass, const String& adduct, bool verbose);
RcppExport SEXP _mzkitcpp_adductize_exact_mass(SEXP exact_massSEXP, SEXP adductSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type exact_mass(exact_massSEXP);
    Rcpp::traits::input_parameter< const String& >::type adduct(adductSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(adductize_exact_mass(exact_mass, adduct, verbose));
    return rcpp_result_gen;
END_RCPP
}
// adductize_formula
double adductize_formula(const String& formula, const String& adduct, bool verbose);
RcppExport SEXP _mzkitcpp_adductize_formula(SEXP formulaSEXP, SEXP adductSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type formula(formulaSEXP);
    Rcpp::traits::input_parameter< const String& >::type adduct(adductSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(adductize_formula(formula, adduct, verbose));
    return rcpp_result_gen;
END_RCPP
}
// adductize_peptide
double adductize_peptide(const String& peptideSequence, const String& adduct, bool verbose);
RcppExport SEXP _mzkitcpp_adductize_peptide(SEXP peptideSequenceSEXP, SEXP adductSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type peptideSequence(peptideSequenceSEXP);
    Rcpp::traits::input_parameter< const String& >::type adduct(adductSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(adductize_peptide(peptideSequence, adduct, verbose));
    return rcpp_result_gen;
END_RCPP
}
// name_summaries
DataFrame name_summaries(const StringVector& compoundName, bool debug);
RcppExport SEXP _mzkitcpp_name_summaries(SEXP compoundNameSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type compoundName(compoundNameSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(name_summaries(compoundName, debug));
    return rcpp_result_gen;
END_RCPP
}
// get_scan_metadata
DataFrame get_scan_metadata(const String& sample_file, const bool& verbose, const bool& debug);
RcppExport SEXP _mzkitcpp_get_scan_metadata(SEXP sample_fileSEXP, SEXP verboseSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type sample_file(sample_fileSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(get_scan_metadata(sample_file, verbose, debug));
    return rcpp_result_gen;
END_RCPP
}
// get_scan_data
DataFrame get_scan_data(const String& sample_file, const int& scan_num, const bool& verbose, const bool& debug);
RcppExport SEXP _mzkitcpp_get_scan_data(SEXP sample_fileSEXP, SEXP scan_numSEXP, SEXP verboseSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type sample_file(sample_fileSEXP);
    Rcpp::traits::input_parameter< const int& >::type scan_num(scan_numSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(get_scan_data(sample_file, scan_num, verbose, debug));
    return rcpp_result_gen;
END_RCPP
}
// get_consensus_spectrum
DataFrame get_consensus_spectrum(const String& sample_file, const IntegerVector& scan_nums, const List& params, const bool& verbose, const bool& debug);
RcppExport SEXP _mzkitcpp_get_consensus_spectrum(SEXP sample_fileSEXP, SEXP scan_numsSEXP, SEXP paramsSEXP, SEXP verboseSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type sample_file(sample_fileSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type scan_nums(scan_numsSEXP);
    Rcpp::traits::input_parameter< const List& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(get_consensus_spectrum(sample_file, scan_nums, params, verbose, debug));
    return rcpp_result_gen;
END_RCPP
}
// get_multi_file_consensus_spectrum
DataFrame get_multi_file_consensus_spectrum(const DataFrame& scans_table, const List& params, const bool& verbose, const bool& debug);
RcppExport SEXP _mzkitcpp_get_multi_file_consensus_spectrum(SEXP scans_tableSEXP, SEXP paramsSEXP, SEXP verboseSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type scans_table(scans_tableSEXP);
    Rcpp::traits::input_parameter< const List& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(get_multi_file_consensus_spectrum(scans_table, params, verbose, debug));
    return rcpp_result_gen;
END_RCPP
}
// get_background_subtracted_scan_data
DataFrame get_background_subtracted_scan_data(const String& sample_file, const int& target_scan_num, const List& params, const bool& verbose, const bool& debug);
RcppExport SEXP _mzkitcpp_get_background_subtracted_scan_data(SEXP sample_fileSEXP, SEXP target_scan_numSEXP, SEXP paramsSEXP, SEXP verboseSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type sample_file(sample_fileSEXP);
    Rcpp::traits::input_parameter< const int& >::type target_scan_num(target_scan_numSEXP);
    Rcpp::traits::input_parameter< const List& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(get_background_subtracted_scan_data(sample_file, target_scan_num, params, verbose, debug));
    return rcpp_result_gen;
END_RCPP
}
// predict_formula
DataFrame predict_formula(const double& mz, const String& adduct, const double& ppm, Nullable<DataFrame> legal_atom_counts, bool debug);
RcppExport SEXP _mzkitcpp_predict_formula(SEXP mzSEXP, SEXP adductSEXP, SEXP ppmSEXP, SEXP legal_atom_countsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type mz(mzSEXP);
    Rcpp::traits::input_parameter< const String& >::type adduct(adductSEXP);
    Rcpp::traits::input_parameter< const double& >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< Nullable<DataFrame> >::type legal_atom_counts(legal_atom_countsSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_formula(mz, adduct, ppm, legal_atom_counts, debug));
    return rcpp_result_gen;
END_RCPP
}
// import_msp_lipids_library
DataFrame import_msp_lipids_library(const String& mspLibraryPath, long totalNumFragments, bool is_include_SMILES, bool is_reformat_to_lipidmaps_2020, int num_digits, bool is_prefer_file_summarizations, bool debug);
RcppExport SEXP _mzkitcpp_import_msp_lipids_library(SEXP mspLibraryPathSEXP, SEXP totalNumFragmentsSEXP, SEXP is_include_SMILESSEXP, SEXP is_reformat_to_lipidmaps_2020SEXP, SEXP num_digitsSEXP, SEXP is_prefer_file_summarizationsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type mspLibraryPath(mspLibraryPathSEXP);
    Rcpp::traits::input_parameter< long >::type totalNumFragments(totalNumFragmentsSEXP);
    Rcpp::traits::input_parameter< bool >::type is_include_SMILES(is_include_SMILESSEXP);
    Rcpp::traits::input_parameter< bool >::type is_reformat_to_lipidmaps_2020(is_reformat_to_lipidmaps_2020SEXP);
    Rcpp::traits::input_parameter< int >::type num_digits(num_digitsSEXP);
    Rcpp::traits::input_parameter< bool >::type is_prefer_file_summarizations(is_prefer_file_summarizationsSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(import_msp_lipids_library(mspLibraryPath, totalNumFragments, is_include_SMILES, is_reformat_to_lipidmaps_2020, num_digits, is_prefer_file_summarizations, debug));
    return rcpp_result_gen;
END_RCPP
}
// export_msp_lipids_library
int export_msp_lipids_library(const String& mspLibraryPath, const DataFrame& mspLibrary, bool observed_intensities, int num_digits, bool debug);
RcppExport SEXP _mzkitcpp_export_msp_lipids_library(SEXP mspLibraryPathSEXP, SEXP mspLibrarySEXP, SEXP observed_intensitiesSEXP, SEXP num_digitsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type mspLibraryPath(mspLibraryPathSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type mspLibrary(mspLibrarySEXP);
    Rcpp::traits::input_parameter< bool >::type observed_intensities(observed_intensitiesSEXP);
    Rcpp::traits::input_parameter< int >::type num_digits(num_digitsSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(export_msp_lipids_library(mspLibraryPath, mspLibrary, observed_intensities, num_digits, debug));
    return rcpp_result_gen;
END_RCPP
}
// mark_fragments_ms2_lib
DataFrame mark_fragments_ms2_lib(const DataFrame& ms2_lib, const StringVector& frags_to_mark, const String& marker, const bool& debug);
RcppExport SEXP _mzkitcpp_mark_fragments_ms2_lib(SEXP ms2_libSEXP, SEXP frags_to_markSEXP, SEXP markerSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type ms2_lib(ms2_libSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type frags_to_mark(frags_to_markSEXP);
    Rcpp::traits::input_parameter< const String& >::type marker(markerSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(mark_fragments_ms2_lib(ms2_lib, frags_to_mark, marker, debug));
    return rcpp_result_gen;
END_RCPP
}
// expand_redundant_fragments_ms2_lib
DataFrame expand_redundant_fragments_ms2_lib(const DataFrame& ms2_lib, const bool& debug);
RcppExport SEXP _mzkitcpp_expand_redundant_fragments_ms2_lib(SEXP ms2_libSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type ms2_lib(ms2_libSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(expand_redundant_fragments_ms2_lib(ms2_lib, debug));
    return rcpp_result_gen;
END_RCPP
}
// expand_redundant_fragments_ms3_lib
DataFrame expand_redundant_fragments_ms3_lib(const DataFrame& ms3_lib, const bool& debug);
RcppExport SEXP _mzkitcpp_expand_redundant_fragments_ms3_lib(SEXP ms3_libSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type ms3_lib(ms3_libSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(expand_redundant_fragments_ms3_lib(ms3_lib, debug));
    return rcpp_result_gen;
END_RCPP
}
// lipidmaps_2020_compound_names
void lipidmaps_2020_compound_names(const DataFrame& ms2_lib, const bool& debug);
RcppExport SEXP _mzkitcpp_lipidmaps_2020_compound_names(SEXP ms2_libSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type ms2_lib(ms2_libSEXP);
    Rcpp::traits::input_parameter< const bool& >::type debug(debugSEXP);
    lipidmaps_2020_compound_names(ms2_lib, debug);
    return R_NilValue;
END_RCPP
}
// groups_to_msp_library
void groups_to_msp_library(const String& mspLibraryPath, const DataFrame& groups, const List& library_params, int num_digits, bool debug);
RcppExport SEXP _mzkitcpp_groups_to_msp_library(SEXP mspLibraryPathSEXP, SEXP groupsSEXP, SEXP library_paramsSEXP, SEXP num_digitsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type mspLibraryPath(mspLibraryPathSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< const List& >::type library_params(library_paramsSEXP);
    Rcpp::traits::input_parameter< int >::type num_digits(num_digitsSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    groups_to_msp_library(mspLibraryPath, groups, library_params, num_digits, debug);
    return R_NilValue;
END_RCPP
}
// loop_injections_to_msp_library
void loop_injections_to_msp_library(const String& mspLibraryPath, const DataFrame& metabolite_data, const List& loop_inj_params, bool is_use_cached_ms2_spectrum, bool is_compute_loop_injection_spectrum, bool print_missing, int num_digits, bool debug);
RcppExport SEXP _mzkitcpp_loop_injections_to_msp_library(SEXP mspLibraryPathSEXP, SEXP metabolite_dataSEXP, SEXP loop_inj_paramsSEXP, SEXP is_use_cached_ms2_spectrumSEXP, SEXP is_compute_loop_injection_spectrumSEXP, SEXP print_missingSEXP, SEXP num_digitsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type mspLibraryPath(mspLibraryPathSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type metabolite_data(metabolite_dataSEXP);
    Rcpp::traits::input_parameter< const List& >::type loop_inj_params(loop_inj_paramsSEXP);
    Rcpp::traits::input_parameter< bool >::type is_use_cached_ms2_spectrum(is_use_cached_ms2_spectrumSEXP);
    Rcpp::traits::input_parameter< bool >::type is_compute_loop_injection_spectrum(is_compute_loop_injection_spectrumSEXP);
    Rcpp::traits::input_parameter< bool >::type print_missing(print_missingSEXP);
    Rcpp::traits::input_parameter< int >::type num_digits(num_digitsSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    loop_injections_to_msp_library(mspLibraryPath, metabolite_data, loop_inj_params, is_use_cached_ms2_spectrum, is_compute_loop_injection_spectrum, print_missing, num_digits, debug);
    return R_NilValue;
END_RCPP
}
// record_set_to_msp_library
void record_set_to_msp_library(const String& mspLibraryPath, const DataFrame& metabolite_data, const List& spectrum_filters, int num_digits, bool debug);
RcppExport SEXP _mzkitcpp_record_set_to_msp_library(SEXP mspLibraryPathSEXP, SEXP metabolite_dataSEXP, SEXP spectrum_filtersSEXP, SEXP num_digitsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const String& >::type mspLibraryPath(mspLibraryPathSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type metabolite_data(metabolite_dataSEXP);
    Rcpp::traits::input_parameter< const List& >::type spectrum_filters(spectrum_filtersSEXP);
    Rcpp::traits::input_parameter< int >::type num_digits(num_digitsSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    record_set_to_msp_library(mspLibraryPath, metabolite_data, spectrum_filters, num_digits, debug);
    return R_NilValue;
END_RCPP
}
// mzk_get_lipid_parameters
String mzk_get_lipid_parameters(float ms1PpmTolr, float ms2PpmTolr, int ms2MinNumMatches, int ms2sn1MinNumMatches, int ms2sn2MinNumMatches, int ms2MinNumAcylMatches, String classAdductParamsCSVFile, bool debug);
RcppExport SEXP _mzkitcpp_mzk_get_lipid_parameters(SEXP ms1PpmTolrSEXP, SEXP ms2PpmTolrSEXP, SEXP ms2MinNumMatchesSEXP, SEXP ms2sn1MinNumMatchesSEXP, SEXP ms2sn2MinNumMatchesSEXP, SEXP ms2MinNumAcylMatchesSEXP, SEXP classAdductParamsCSVFileSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type ms1PpmTolr(ms1PpmTolrSEXP);
    Rcpp::traits::input_parameter< float >::type ms2PpmTolr(ms2PpmTolrSEXP);
    Rcpp::traits::input_parameter< int >::type ms2MinNumMatches(ms2MinNumMatchesSEXP);
    Rcpp::traits::input_parameter< int >::type ms2sn1MinNumMatches(ms2sn1MinNumMatchesSEXP);
    Rcpp::traits::input_parameter< int >::type ms2sn2MinNumMatches(ms2sn2MinNumMatchesSEXP);
    Rcpp::traits::input_parameter< int >::type ms2MinNumAcylMatches(ms2MinNumAcylMatchesSEXP);
    Rcpp::traits::input_parameter< String >::type classAdductParamsCSVFile(classAdductParamsCSVFileSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(mzk_get_lipid_parameters(ms1PpmTolr, ms2PpmTolr, ms2MinNumMatches, ms2sn1MinNumMatches, ms2sn2MinNumMatches, ms2MinNumAcylMatches, classAdductParamsCSVFile, debug));
    return rcpp_result_gen;
END_RCPP
}
// mzk_get_isotope_parameters
String mzk_get_isotope_parameters(const List& params, bool debug);
RcppExport SEXP _mzkitcpp_mzk_get_isotope_parameters(SEXP paramsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(mzk_get_isotope_parameters(params, debug));
    return rcpp_result_gen;
END_RCPP
}
// find_duplicate_peaks
DataFrame find_duplicate_peaks(const DataFrame& peaks_combined, const double mz_tol, const double rt_tol, const double intensity_tol, bool verbose, bool debug);
RcppExport SEXP _mzkitcpp_find_duplicate_peaks(SEXP peaks_combinedSEXP, SEXP mz_tolSEXP, SEXP rt_tolSEXP, SEXP intensity_tolSEXP, SEXP verboseSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type peaks_combined(peaks_combinedSEXP);
    Rcpp::traits::input_parameter< const double >::type mz_tol(mz_tolSEXP);
    Rcpp::traits::input_parameter< const double >::type rt_tol(rt_tolSEXP);
    Rcpp::traits::input_parameter< const double >::type intensity_tol(intensity_tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(find_duplicate_peaks(peaks_combined, mz_tol, rt_tol, intensity_tol, verbose, debug));
    return rcpp_result_gen;
END_RCPP
}
// merge_split_groups
List merge_split_groups(const DataFrame& peaks, const double mz_tol, const double rt_tol, const double groupMergeOverlap, bool verbose, bool debug);
RcppExport SEXP _mzkitcpp_merge_split_groups(SEXP peaksSEXP, SEXP mz_tolSEXP, SEXP rt_tolSEXP, SEXP groupMergeOverlapSEXP, SEXP verboseSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type peaks(peaksSEXP);
    Rcpp::traits::input_parameter< const double >::type mz_tol(mz_tolSEXP);
    Rcpp::traits::input_parameter< const double >::type rt_tol(rt_tolSEXP);
    Rcpp::traits::input_parameter< const double >::type groupMergeOverlap(groupMergeOverlapSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(merge_split_groups(peaks, mz_tol, rt_tol, groupMergeOverlap, verbose, debug));
    return rcpp_result_gen;
END_RCPP
}
// qqq_peaks
DataFrame qqq_peaks(String& mzml_file, DataFrame& query_transitions, List& params, bool debug, bool verbose);
RcppExport SEXP _mzkitcpp_qqq_peaks(SEXP mzml_fileSEXP, SEXP query_transitionsSEXP, SEXP paramsSEXP, SEXP debugSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String& >::type mzml_file(mzml_fileSEXP);
    Rcpp::traits::input_parameter< DataFrame& >::type query_transitions(query_transitionsSEXP);
    Rcpp::traits::input_parameter< List& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(qqq_peaks(mzml_file, query_transitions, params, debug, verbose));
    return rcpp_result_gen;
END_RCPP
}
// update_rts
DataFrame update_rts(const DataFrame& rt_update_key, const NumericVector& original_rts, const IntegerVector& sample_ids, bool debug);
RcppExport SEXP _mzkitcpp_update_rts(SEXP rt_update_keySEXP, SEXP original_rtsSEXP, SEXP sample_idsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type rt_update_key(rt_update_keySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type original_rts(original_rtsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type sample_ids(sample_idsSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(update_rts(rt_update_key, original_rts, sample_ids, debug));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mzkitcpp_DI_ms2_ranges", (DL_FUNC) &_mzkitcpp_DI_ms2_ranges, 3},
    {"_mzkitcpp_DI_ms3_targets", (DL_FUNC) &_mzkitcpp_DI_ms3_targets, 2},
    {"_mzkitcpp_DI_slice_library", (DL_FUNC) &_mzkitcpp_DI_slice_library, 4},
    {"_mzkitcpp_DI_unslice_library", (DL_FUNC) &_mzkitcpp_DI_unslice_library, 2},
    {"_mzkitcpp_DI_encoded_search_params", (DL_FUNC) &_mzkitcpp_DI_encoded_search_params, 2},
    {"_mzkitcpp_DI_summarized_compounds", (DL_FUNC) &_mzkitcpp_DI_summarized_compounds, 5},
    {"_mzkitcpp_DI_peakgroups_and_peaks", (DL_FUNC) &_mzkitcpp_DI_peakgroups_and_peaks, 8},
    {"_mzkitcpp_DI_ms3_peakgroups_and_peaks", (DL_FUNC) &_mzkitcpp_DI_ms3_peakgroups_and_peaks, 9},
    {"_mzkitcpp_DI_pipeline", (DL_FUNC) &_mzkitcpp_DI_pipeline, 9},
    {"_mzkitcpp_DI_pipeline_ms3_search", (DL_FUNC) &_mzkitcpp_DI_pipeline_ms3_search, 7},
    {"_mzkitcpp_DI_search_lib", (DL_FUNC) &_mzkitcpp_DI_search_lib, 10},
    {"_mzkitcpp_DI_ms1_and_ms2_intensity", (DL_FUNC) &_mzkitcpp_DI_ms1_and_ms2_intensity, 11},
    {"_mzkitcpp_DI_ms_intensity", (DL_FUNC) &_mzkitcpp_DI_ms_intensity, 10},
    {"_mzkitcpp_DI_ms1_range_intensity", (DL_FUNC) &_mzkitcpp_DI_ms1_range_intensity, 5},
    {"_mzkitcpp_DI_ms2_range_id", (DL_FUNC) &_mzkitcpp_DI_ms2_range_id, 3},
    {"_mzkitcpp_DI_ms3_intensity", (DL_FUNC) &_mzkitcpp_DI_ms3_intensity, 10},
    {"_mzkitcpp_DI_file_info", (DL_FUNC) &_mzkitcpp_DI_file_info, 2},
    {"_mzkitcpp_get_eic", (DL_FUNC) &_mzkitcpp_get_eic, 8},
    {"_mzkitcpp_reextract_peaks", (DL_FUNC) &_mzkitcpp_reextract_peaks, 8},
    {"_mzkitcpp_repick_peaks", (DL_FUNC) &_mzkitcpp_repick_peaks, 4},
    {"_mzkitcpp_get_ms2_scans", (DL_FUNC) &_mzkitcpp_get_ms2_scans, 4},
    {"_mzkitcpp_get_standard_rts", (DL_FUNC) &_mzkitcpp_get_standard_rts, 7},
    {"_mzkitcpp_get_last_rts", (DL_FUNC) &_mzkitcpp_get_last_rts, 3},
    {"_mzkitcpp_ISO_isotope_matrices", (DL_FUNC) &_mzkitcpp_ISO_isotope_matrices, 8},
    {"_mzkitcpp_maldesi_search", (DL_FUNC) &_mzkitcpp_maldesi_search, 5},
    {"_mzkitcpp_maldesi_isotopic_envelope_finder", (DL_FUNC) &_mzkitcpp_maldesi_isotopic_envelope_finder, 4},
    {"_mzkitcpp_maldesi_create_modified_mzML", (DL_FUNC) &_mzkitcpp_maldesi_create_modified_mzML, 5},
    {"_mzkitcpp_smoothed_series", (DL_FUNC) &_mzkitcpp_smoothed_series, 4},
    {"_mzkitcpp_monoiosotopic_mass", (DL_FUNC) &_mzkitcpp_monoiosotopic_mass, 3},
    {"_mzkitcpp_precursor_mass", (DL_FUNC) &_mzkitcpp_precursor_mass, 4},
    {"_mzkitcpp_exact_mass", (DL_FUNC) &_mzkitcpp_exact_mass, 2},
    {"_mzkitcpp_exact_mass_peptide", (DL_FUNC) &_mzkitcpp_exact_mass_peptide, 2},
    {"_mzkitcpp_envelope_dist_peptide", (DL_FUNC) &_mzkitcpp_envelope_dist_peptide, 3},
    {"_mzkitcpp_adductize_exact_mass", (DL_FUNC) &_mzkitcpp_adductize_exact_mass, 3},
    {"_mzkitcpp_adductize_formula", (DL_FUNC) &_mzkitcpp_adductize_formula, 3},
    {"_mzkitcpp_adductize_peptide", (DL_FUNC) &_mzkitcpp_adductize_peptide, 3},
    {"_mzkitcpp_name_summaries", (DL_FUNC) &_mzkitcpp_name_summaries, 2},
    {"_mzkitcpp_get_scan_metadata", (DL_FUNC) &_mzkitcpp_get_scan_metadata, 3},
    {"_mzkitcpp_get_scan_data", (DL_FUNC) &_mzkitcpp_get_scan_data, 4},
    {"_mzkitcpp_get_consensus_spectrum", (DL_FUNC) &_mzkitcpp_get_consensus_spectrum, 5},
    {"_mzkitcpp_get_multi_file_consensus_spectrum", (DL_FUNC) &_mzkitcpp_get_multi_file_consensus_spectrum, 4},
    {"_mzkitcpp_get_background_subtracted_scan_data", (DL_FUNC) &_mzkitcpp_get_background_subtracted_scan_data, 5},
    {"_mzkitcpp_predict_formula", (DL_FUNC) &_mzkitcpp_predict_formula, 5},
    {"_mzkitcpp_import_msp_lipids_library", (DL_FUNC) &_mzkitcpp_import_msp_lipids_library, 7},
    {"_mzkitcpp_export_msp_lipids_library", (DL_FUNC) &_mzkitcpp_export_msp_lipids_library, 5},
    {"_mzkitcpp_mark_fragments_ms2_lib", (DL_FUNC) &_mzkitcpp_mark_fragments_ms2_lib, 4},
    {"_mzkitcpp_expand_redundant_fragments_ms2_lib", (DL_FUNC) &_mzkitcpp_expand_redundant_fragments_ms2_lib, 2},
    {"_mzkitcpp_expand_redundant_fragments_ms3_lib", (DL_FUNC) &_mzkitcpp_expand_redundant_fragments_ms3_lib, 2},
    {"_mzkitcpp_lipidmaps_2020_compound_names", (DL_FUNC) &_mzkitcpp_lipidmaps_2020_compound_names, 2},
    {"_mzkitcpp_groups_to_msp_library", (DL_FUNC) &_mzkitcpp_groups_to_msp_library, 5},
    {"_mzkitcpp_loop_injections_to_msp_library", (DL_FUNC) &_mzkitcpp_loop_injections_to_msp_library, 8},
    {"_mzkitcpp_record_set_to_msp_library", (DL_FUNC) &_mzkitcpp_record_set_to_msp_library, 5},
    {"_mzkitcpp_mzk_get_lipid_parameters", (DL_FUNC) &_mzkitcpp_mzk_get_lipid_parameters, 8},
    {"_mzkitcpp_mzk_get_isotope_parameters", (DL_FUNC) &_mzkitcpp_mzk_get_isotope_parameters, 2},
    {"_mzkitcpp_find_duplicate_peaks", (DL_FUNC) &_mzkitcpp_find_duplicate_peaks, 6},
    {"_mzkitcpp_merge_split_groups", (DL_FUNC) &_mzkitcpp_merge_split_groups, 6},
    {"_mzkitcpp_qqq_peaks", (DL_FUNC) &_mzkitcpp_qqq_peaks, 5},
    {"_mzkitcpp_update_rts", (DL_FUNC) &_mzkitcpp_update_rts, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_mzkitcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
