# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DI_ms2_ranges <- function(filename, collapse_overlaps = FALSE, debug = FALSE) {
    .Call(`_mzkitcpp_DI_ms2_ranges`, filename, collapse_overlaps, debug)
}

DI_ms3_targets <- function(filename, debug = FALSE) {
    .Call(`_mzkitcpp_DI_ms3_targets`, filename, debug)
}

DI_slice_library <- function(ms2_ranges, lipid_library, is_mark_unique_as_diagnostic = FALSE, debug = FALSE) {
    .Call(`_mzkitcpp_DI_slice_library`, ms2_ranges, lipid_library, is_mark_unique_as_diagnostic, debug)
}

DI_unslice_library <- function(sliced_lib, debug = FALSE) {
    .Call(`_mzkitcpp_DI_unslice_library`, sliced_lib, debug)
}

DI_encoded_search_params <- function(search_params, debug = FALSE) {
    .Call(`_mzkitcpp_DI_encoded_search_params`, search_params, debug)
}

DI_summarized_compounds <- function(di_search_results, search_lib, ms2_ranges, adducts_file, debug = FALSE) {
    .Call(`_mzkitcpp_DI_summarized_compounds`, di_search_results, search_lib, ms2_ranges, adducts_file, debug)
}

DI_peakgroups_and_peaks <- function(di_search_results_no_frags, first_peak_id, first_group_id, num_peakgroups, search_name, library_name, verbose = TRUE, debug = FALSE) {
    .Call(`_mzkitcpp_DI_peakgroups_and_peaks`, di_search_results_no_frags, first_peak_id, first_group_id, num_peakgroups, search_name, library_name, verbose, debug)
}

DI_ms3_peakgroups_and_peaks <- function(ms3_search_results_no_frags, first_peak_id, first_group_id, num_peakgroups, num_peaks, search_name, library_name, verbose = TRUE, debug = FALSE) {
    .Call(`_mzkitcpp_DI_ms3_peakgroups_and_peaks`, ms3_search_results_no_frags, first_peak_id, first_group_id, num_peakgroups, num_peaks, search_name, library_name, verbose, debug)
}

DI_pipeline <- function(samples, ms2_ranges, is_sliced_lib, is_search_params, sliced_lib, search_params, adducts_file, fragment_group_id_decimals = 2L, debug = FALSE) {
    .Call(`_mzkitcpp_DI_pipeline`, samples, ms2_ranges, is_sliced_lib, is_search_params, sliced_lib, search_params, adducts_file, fragment_group_id_decimals, debug)
}

DI_pipeline_ms3_search <- function(samples, is_lib, is_search_params, search_lib, search_params, adducts_file, debug = FALSE) {
    .Call(`_mzkitcpp_DI_pipeline_ms3_search`, samples, is_lib, is_search_params, search_lib, search_params, adducts_file, debug)
}

DI_search_lib <- function(samples, mspLibrary, ms1_ppm = 3, ms2_ppm = 20, ms1_scan_filter = "", scan_intensity_summary = "topOne", ignore_empty = TRUE, m_minus_one_intensity_threshold = 0.0, m_minus_two_intensity_threshold = 0.0, debug = FALSE) {
    .Call(`_mzkitcpp_DI_search_lib`, samples, mspLibrary, ms1_ppm, ms2_ppm, ms1_scan_filter, scan_intensity_summary, ignore_empty, m_minus_one_intensity_threshold, m_minus_two_intensity_threshold, debug)
}

DI_ms1_and_ms2_intensity <- function(samples, ms1_mzs, ms2_mzs, ms1_ppm = 10, ms2_ppm = 20, ms1_scan_filter = "", scan_intensity_summary = "topOne", ignore_empty = TRUE, m_minus_one_intensity_threshold = 0, m_minus_two_intensity_threshold = 0, debug = FALSE) {
    .Call(`_mzkitcpp_DI_ms1_and_ms2_intensity`, samples, ms1_mzs, ms2_mzs, ms1_ppm, ms2_ppm, ms1_scan_filter, scan_intensity_summary, ignore_empty, m_minus_one_intensity_threshold, m_minus_two_intensity_threshold, debug)
}

DI_ms_intensity <- function(samples, mzs, ppm, scan_filter, scan_intensity_summary = "topOne", msLevel = 1L, m_minus_one_intensity_threshold = 0, m_minus_two_intensity_threshold = 0, prec_mzs = numeric(0), debug = FALSE) {
    .Call(`_mzkitcpp_DI_ms_intensity`, samples, mzs, ppm, scan_filter, scan_intensity_summary, msLevel, m_minus_one_intensity_threshold, m_minus_two_intensity_threshold, prec_mzs, debug)
}

DI_ms1_range_intensity <- function(samples, prec_mz_min, prec_mz_max, scan_width = -1L, debug = FALSE) {
    .Call(`_mzkitcpp_DI_ms1_range_intensity`, samples, prec_mz_min, prec_mz_max, scan_width, debug)
}

DI_ms2_range_id <- function(di_ms2_ranges_table, prec_mzs, debug = FALSE) {
    .Call(`_mzkitcpp_DI_ms2_range_id`, di_ms2_ranges_table, prec_mzs, debug)
}

DI_ms3_intensity <- function(samples, ms1_mzs, ms2_mzs, ms3_mzs, ms3AnalysisMs1PrecursorPpmTolr = 20, ms3PrecursorPpmTolr = 20, ms3FragTol = 0.5, isMs3FragTypeInPpm = FALSE, extraction_type = "ALL", debug = FALSE) {
    .Call(`_mzkitcpp_DI_ms3_intensity`, samples, ms1_mzs, ms2_mzs, ms3_mzs, ms3AnalysisMs1PrecursorPpmTolr, ms3PrecursorPpmTolr, ms3FragTol, isMs3FragTypeInPpm, extraction_type, debug)
}

DI_file_info <- function(samples, debug = FALSE) {
    .Call(`_mzkitcpp_DI_file_info`, samples, debug)
}

get_eic <- function(samples, mzmin, mzmax, rtmin, rtmax, mslevel = 1L, smoothWindow = 5L, debug = FALSE) {
    .Call(`_mzkitcpp_get_eic`, samples, mzmin, mzmax, rtmin, rtmax, mslevel, smoothWindow, debug)
}

reextract_peaks <- function(compound_list, sample_file, intensity_type = "peakAreaTop", mslevel = 1L, baselineSmoothingWindow = 5L, baselineDropTopX = 60L, verbose = TRUE, debug = FALSE) {
    .Call(`_mzkitcpp_reextract_peaks`, compound_list, sample_file, intensity_type, mslevel, baselineSmoothingWindow, baselineDropTopX, verbose, debug)
}

repick_peaks <- function(peaks_to_repick, encodedParams = "", verbose = TRUE, debug = FALSE) {
    .Call(`_mzkitcpp_repick_peaks`, peaks_to_repick, encodedParams, verbose, debug)
}

get_ms2_scans <- function(samples_table, ppm = 20, dataLimit = 2000L, debug = FALSE) {
    .Call(`_mzkitcpp_get_ms2_scans`, samples_table, ppm, dataLimit, debug)
}

get_standard_rts <- function(samples, standards, mzTolerance = 10, rtTolerance = 9999, minIntensity = 0, verbose = FALSE, debug = FALSE) {
    .Call(`_mzkitcpp_get_standard_rts`, samples, standards, mzTolerance, rtTolerance, minIntensity, verbose, debug)
}

get_last_rts <- function(samples, verbose = FALSE, debug = FALSE) {
    .Call(`_mzkitcpp_get_last_rts`, samples, verbose, debug)
}

ISO_isotope_matrices <- function(mzML_directory, sample_tbl, peak_tbl, group_tbl, unlabeled_samples, labeled_samples, params, debug = TRUE) {
    .Call(`_mzkitcpp_ISO_isotope_matrices`, mzML_directory, sample_tbl, peak_tbl, group_tbl, unlabeled_samples, labeled_samples, params, debug)
}

maldesi_search <- function(sample_file, library, search_params, verbose = TRUE, debug = FALSE) {
    .Call(`_mzkitcpp_maldesi_search`, sample_file, library, search_params, verbose, debug)
}

maldesi_isotopic_envelope_finder <- function(sample_file, params, verbose = TRUE, debug = FALSE) {
    .Call(`_mzkitcpp_maldesi_isotopic_envelope_finder`, sample_file, params, verbose, debug)
}

maldesi_create_modified_mzML <- function(sample_file, modified_sample_file, modification_params, verbose = TRUE, debug = FALSE) {
    invisible(.Call(`_mzkitcpp_maldesi_create_modified_mzML`, sample_file, modified_sample_file, modification_params, verbose, debug))
}

smoothed_series <- function(data, types, windowSizes, debug = FALSE) {
    .Call(`_mzkitcpp_smoothed_series`, data, types, windowSizes, debug)
}

monoiosotopic_mass <- function(formula, num_digits = 7L, debug = FALSE) {
    .Call(`_mzkitcpp_monoiosotopic_mass`, formula, num_digits, debug)
}

precursor_mass <- function(formula, adduct, num_digits = 7L, debug = FALSE) {
    .Call(`_mzkitcpp_precursor_mass`, formula, adduct, num_digits, debug)
}

exact_mass <- function(formula, verbose = FALSE) {
    .Call(`_mzkitcpp_exact_mass`, formula, verbose)
}

adductize_exact_mass <- function(exact_mass, adduct, verbose = FALSE) {
    .Call(`_mzkitcpp_adductize_exact_mass`, exact_mass, adduct, verbose)
}

adductize_formula <- function(formula, adduct, verbose = FALSE) {
    .Call(`_mzkitcpp_adductize_formula`, formula, adduct, verbose)
}

name_summaries <- function(compoundName, debug = FALSE) {
    .Call(`_mzkitcpp_name_summaries`, compoundName, debug)
}

get_scan_metadata <- function(sample_file, verbose = TRUE, debug = FALSE) {
    .Call(`_mzkitcpp_get_scan_metadata`, sample_file, verbose, debug)
}

get_scan_data <- function(sample_file, scan_num, verbose = TRUE, debug = FALSE) {
    .Call(`_mzkitcpp_get_scan_data`, sample_file, scan_num, verbose, debug)
}

get_background_subtracted_scan_data <- function(sample_file, target_scan_num, background_scan_num, ppm_tol, verbose = TRUE, debug = FALSE) {
    .Call(`_mzkitcpp_get_background_subtracted_scan_data`, sample_file, target_scan_num, background_scan_num, ppm_tol, verbose, debug)
}

predict_formula <- function(mz, adduct, ppm = 10.0, legal_atom_counts = NULL, debug = FALSE) {
    .Call(`_mzkitcpp_predict_formula`, mz, adduct, ppm, legal_atom_counts, debug)
}

import_msp_lipids_library <- function(mspLibraryPath, totalNumFragments = -1L, is_include_SMILES = FALSE, is_reformat_to_lipidmaps_2020 = FALSE, num_digits = 7L, is_prefer_file_summarizations = FALSE, debug = FALSE) {
    .Call(`_mzkitcpp_import_msp_lipids_library`, mspLibraryPath, totalNumFragments, is_include_SMILES, is_reformat_to_lipidmaps_2020, num_digits, is_prefer_file_summarizations, debug)
}

export_msp_lipids_library <- function(mspLibraryPath, mspLibrary, observed_intensities = TRUE, num_digits = 7L, debug = FALSE) {
    .Call(`_mzkitcpp_export_msp_lipids_library`, mspLibraryPath, mspLibrary, observed_intensities, num_digits, debug)
}

mark_fragments_ms2_lib <- function(ms2_lib, frags_to_mark, marker, debug = FALSE) {
    .Call(`_mzkitcpp_mark_fragments_ms2_lib`, ms2_lib, frags_to_mark, marker, debug)
}

expand_redundant_fragments_ms2_lib <- function(ms2_lib, debug = FALSE) {
    .Call(`_mzkitcpp_expand_redundant_fragments_ms2_lib`, ms2_lib, debug)
}

expand_redundant_fragments_ms3_lib <- function(ms3_lib, debug = FALSE) {
    .Call(`_mzkitcpp_expand_redundant_fragments_ms3_lib`, ms3_lib, debug)
}

lipidmaps_2020_compound_names <- function(ms2_lib, debug = FALSE) {
    invisible(.Call(`_mzkitcpp_lipidmaps_2020_compound_names`, ms2_lib, debug))
}

groups_to_msp_library <- function(mspLibraryPath, groups, library_params, num_digits = 7L, debug = FALSE) {
    invisible(.Call(`_mzkitcpp_groups_to_msp_library`, mspLibraryPath, groups, library_params, num_digits, debug))
}

loop_injections_to_msp_library <- function(mspLibraryPath, metabolite_data, loop_inj_params, is_use_cached_ms2_spectrum = FALSE, is_compute_loop_injection_spectrum = TRUE, print_missing = FALSE, num_digits = 7L, debug = FALSE) {
    invisible(.Call(`_mzkitcpp_loop_injections_to_msp_library`, mspLibraryPath, metabolite_data, loop_inj_params, is_use_cached_ms2_spectrum, is_compute_loop_injection_spectrum, print_missing, num_digits, debug))
}

record_set_to_msp_library <- function(mspLibraryPath, metabolite_data, spectrum_filters, num_digits = 7L, debug = FALSE) {
    invisible(.Call(`_mzkitcpp_record_set_to_msp_library`, mspLibraryPath, metabolite_data, spectrum_filters, num_digits, debug))
}

mzk_get_lipid_parameters <- function(ms1PpmTolr, ms2PpmTolr, ms2MinNumMatches, ms2sn1MinNumMatches, ms2sn2MinNumMatches, ms2MinNumAcylMatches, classAdductParamsCSVFile, debug = FALSE) {
    .Call(`_mzkitcpp_mzk_get_lipid_parameters`, ms1PpmTolr, ms2PpmTolr, ms2MinNumMatches, ms2sn1MinNumMatches, ms2sn2MinNumMatches, ms2MinNumAcylMatches, classAdductParamsCSVFile, debug)
}

mzk_get_isotope_parameters <- function(params, debug = FALSE) {
    .Call(`_mzkitcpp_mzk_get_isotope_parameters`, params, debug)
}

find_duplicate_peaks <- function(peaks_combined, mz_tol = 5.0, rt_tol = 0.1, intensity_tol = 0.01, verbose = TRUE, debug = FALSE) {
    .Call(`_mzkitcpp_find_duplicate_peaks`, peaks_combined, mz_tol, rt_tol, intensity_tol, verbose, debug)
}

merge_split_groups <- function(peaks, mz_tol = 5.0, rt_tol = 0.1, groupMergeOverlap = 0.8, verbose = TRUE, debug = FALSE) {
    .Call(`_mzkitcpp_merge_split_groups`, peaks, mz_tol, rt_tol, groupMergeOverlap, verbose, debug)
}

qqq_peaks <- function(mzml_file, query_transitions, params, debug = FALSE, verbose = FALSE) {
    .Call(`_mzkitcpp_qqq_peaks`, mzml_file, query_transitions, params, debug, verbose)
}

update_rts <- function(rt_update_key, original_rts, sample_ids, debug = FALSE) {
    .Call(`_mzkitcpp_update_rts`, rt_update_key, original_rts, sample_ids, debug)
}

